//
//  WPNotificationCategoryHelper.h
//  WonderPush
//
//  Created by Stéphane JAIS on 27/02/2020.
//  Copyright © 2020 WonderPush. All rights reserved.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

// FIXME: in an ideal world, this class would not exist and its methods would be part of WPNotificationCategoryManager. WPNotificationCategoryManager would be shipped into WonderPush.framework and would be linked from WonderPushExtension.framework. While this is easily achieved with a regular framework integration, it is unfortunately impossible with CocoaPods. We tried creating a "Common" subspec within the WonderPush pod with this class inside and introduce a dependency in the WonderPushExtension pod to "WonderPush/Common" but that would prevent our customers from creating an archive because of these issues: https://github.com/CocoaPods/CocoaPods/issues/8206 and https://openradar.appspot.com/radar?id=5038526135533568

@interface WPNotificationCategoryHelper : NSObject
+ (instancetype) sharedInstance;
/**
 Returns true when the action identifier was generated by WonderPush
 */
- (BOOL)isWonderPushActionIdentifier:(NSString *)actionIdentifier;
/**
 Returns the index of the button with the provided action identifier, or -1 if the provided identifier doesn't fit the format
 */
- (NSInteger)indexOfButtonWithActionIdentifier:(NSString *)actionIdentifier;
@end

NS_ASSUME_NONNULL_END
