//
//  WPNotificationCategoryManager.h
//  WonderPush
//
//  Created by Stéphane JAIS on 24/02/2020.
//  Copyright © 2020 WonderPush. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <UserNotifications/UserNotifications.h>

NS_ASSUME_NONNULL_BEGIN

@interface WPNotificationCategoryManager : NSObject
+ (instancetype) sharedInstance;
/**
 Returns an action identifier for the button at provided index
 */
- (NSString *)actionIdentifierForButtonAtIndex:(NSUInteger)index;
/**
 Returns true when the action identifier was generated by WonderPush
 */
- (BOOL)isWonderPushActionIdentifier:(NSString *)actionIdentifier;
/**
 Returns the index of the button with the provided action identifier, or -1 if the provided identifier doesn't fit the format
 */
- (NSInteger)indexOfButtonWithActionIdentifier:(NSString *)actionIdentifier;
/**
 Creates and register a UNNotificationCategory for the provided notificationId and actions
 */
- (UNNotificationCategory *_Nullable) registerNotificationCategoryIdentifierWithNotificationId:(NSString *)notificationId actions:(NSArray<UNNotificationAction *> *)actions API_AVAILABLE(ios(10.0));
@end
NS_ASSUME_NONNULL_END
